backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "rates"
    label: "Rates"
    files:
      - label: "Currency Rates"
        name: "rates"
        file: "rates.json"
        fields:
          - { label: "USD Buy", name: "usd_buy", widget: "string" }
          - { label: "USD Sell", name: "usd_sell", widget: "string" }
